name: Pull Request Checks

on:
  pull_request:

jobs:
  check-moonwave:
    name: Check Moonwave Compiles
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm install -g moonwave

      - name: Check Moonwave Compiles
        run: moonwave build
